site_name: Sonosus's Synth DIY documentation
site_description: 'Documentation for my synth-DIY modules and projects.'
site_author: 'Sonosus'
docs_dir: docs/
repo_name: 'sonosus/module-docs'
repo_url: 'https://github.com/sonosus/module-docs'
nav:
    - Home: index.md
    - 'Modules':
      - 'Kosmic Mutator': 'vcdo.md'
      - 'Kosmic Superspreader': 'spreader.md'
      - '3340 VCO Breakout': '3340breakout.md'
theme:
  name: 'material'
  features:
      - navigation.tracking
      - toc.integrate
      - navigation.expand
  palette:
    - accent: orange
    - primary: red
markdown_extensions:
    - toc:
        permalink: "%"
        permalink: True
    - tables
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/sonosus
    analytics:
      provider: google
      property: G-7KP96YZFCX
