site_name: Sonosus's Synth DIY site
site_description: 'A docs test'
site_author: 'Sonosus'
docs_dir: docs/
repo_name: 'sonosus/module-docs'
repo_url: 'https://github.com/sonosus/module-docs'
nav:
    - Home: index.md
    - Modules: modules.md
theme:
  name: 'material'
